controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

home:
    path: /
    controller: App\Controller\homeController::home

informatique:
    path: /informatique
    controller: App\Controller\informatiqueController::informatique

composantpc:
    path: /informatique/composantpc
    controller: App\Controller\composantpcController::composantpc

gpu:
    path: /informatique/composantpc/gpu
    controller: App\Controller\gpuController::gpu